/** @format */

import Head from 'next/head';
import { PropsWithChildren } from 'react';
import SideBar from './SideBar';

export const Layout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex">
        <SideBar sideLinks={[]}></SideBar>
        <main>{children}</main>
      </div>
    </>
  );
};
